spring.application.name=Uttar

free.api.key = apf_l7d4ukgb37tnci1dlrwhlwyi
free.api.url = https://apifreellm.com/api/v1/chat

premium.api.key = apf_l7d4ukgb37tnci1dlrwhlwyi
premium.api.url = https://apifreellm.com/api/v1/chat

openrouter.api.key = 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
openrouter.api.url = https://openrouter.ai/api/v1/chat/completions

#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

